#!/usr/bin/python
# Copyright 2006 John Duda 

# This file is part of Infoshopkeeper.

# Infoshopkeeper is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or any later version.

# Infoshopkeeper is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Infoshopkeeper; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301
# USA

#Boa:App:BoaApp

from config import configuration
from wxPython.wx import *

#import wx.SingleInstanceChecker
import wx

import sys
import os

import wxFrame1
import logging
import logging.handlers

modules ={'item': [0, '', 'item.py'],
 'numericDisplay': [0, '', 'numericDisplay.py'],
 'orderDisplay': [0, '', 'orderDisplay.py'],
 'wxFrame1': [1, 'Main frame of Application', 'wxFrame1.py']}

class BoaApp(wxApp):
    logger=None


    def OnInit(self):
    	self.checker=wx.SingleInstanceChecker("InfoShopKeeper-%s" % (wx.GetUserId()))
	if (self.checker.IsAnotherRunning()):
		print "another instance is running"
		sys.exit(0)
	
        # Terrorize yuppies users
        wxInitAllImageHandlers()
	
	#create logger
	self.logger = logging.getLogger("Error Log")
	self.logger.setLevel(logging.INFO)
	#create handler
	fileHandler = logging.handlers.RotatingFileHandler("Infoshopkeeper.log", maxBytes=1048576, backupCount=5)
	#create formatter
	formatter=logging.Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s")
	fileHandler.setFormatter(formatter)
	self.logger.addHandler(fileHandler)
	
	bitmapfile=os.path.join(os.path.dirname(os.path.abspath(__file__)), "logo.png")
	try:
		self.bitmap = wxBitmap(bitmapfile, wxBITMAP_TYPE_PNG)
	except:
		pass
	print self.bitmap
	
        if (self.bitmap):
		try:
			splash = wx.SplashScreen(self.bitmap,
				wxSPLASH_CENTRE_ON_SCREEN|wxSPLASH_TIMEOUT,
				6000, NULL, -1, wxDefaultPosition, wxDefaultSize,
				wxFRAME_NO_TASKBAR|wxSTAY_ON_TOP)
		except:
			pass
		
        self.main = wxFrame1.create(None)
        # needed when running from Boa under Windows 9X
        self.SetTopWindow(self.main)
        self.main.Show();
        return True

def main():

   logfile=os.path.join(os.path.dirname(os.path.abspath(__file__)), "infoshopkeeper.log")
   application = BoaApp(redirect=0, filename=logfile)
   #self.logger.info("Test")
   try:
       application.MainLoop()
   except Exception, e:
      
       #logger.exception("An error occurred")
       raise


if __name__ == '__main__':
    main()
