#!/bin/bash
WD1=$PWD
if [[ $(pwd) =~ (.*/git_repos/infoshopkeeper)(.*) ]]; then cd ${BASH_REMATCH[1]};  fi
#cd ~mkapes/Documents/Developer/git_repos/infoshopkeeper/inventoryserver
cheetah compile -R
cd $WD1
whereis apache2ctl >/dev/null
if [ $? -eq 0 ]; then echo "apache2ctl"; sudo apache2ctl graceful; fi;

whereis apachectl >/dev/null
if [ $? -eq 0 ]; then echo "apachectl"; sudo apachectl graceful; fi;