#!/bin/bash
rsync  -avz -L --exclude="*.pyc" --exclude="infoshopkeeper.log" --exclude="__init__.py" --exclude="*.log*" --exclude="*.conf" --exclude="*.wsgi" --exclude='etc.py' --exclude='css' --exclude='javascript' --exclude='development-bundle'  --exclude='js' --exclude='recomp'  --cvs-exclude  --inplace /home/tech/Developer/git_repos/infoshopkeeper /home/woodenshoe
./recomp
