#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from Cheetah.compat import unicode
from .EditTemplate import EditTemplate
from objects.author import Author

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '3.0.0'
__CHEETAH_versionTuple__ = (3, 0, 0, 'final', 1)
__CHEETAH_genTime__ = 1510105565.7044423
__CHEETAH_genTimestamp__ = 'Wed Nov  8 01:46:05 2017'
__CHEETAH_src__ = 'AuthorEditTemplate.tmpl'
__CHEETAH_srcLastModified__ = 'Wed Nov  8 00:51:24 2017'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class AuthorEditTemplate(EditTemplate):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(AuthorEditTemplate, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def headscripts(self, **KWS):



        ## CHEETAH: generated from #def headscripts at line 7, col 1.
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        _v = VFN(VFFSL(SL,"EditTemplate",True),"headscripts",False)(VFFSL(SL,"self",True)) # '$EditTemplate.headscripts($self)' on line 8, col 1
        if _v is not None: write(_filter(_v, rawExpr='$EditTemplate.headscripts($self)')) # from line 8, col 1.
        write('''
<script type="text/javascript">
    jQuery(\'#id_authorName\').autocomplete({
        source: \'author_autocomplete\',
    });   
</script>
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        

    def pagetitle(self, **KWS):



        ## CHEETAH: generated from #def pagetitle at line 16, col 1.
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        if not VFFSL(SL,"new_author",True): # generated from line 17, col 1
            write('''Editing author ''')
            _v = VFFSL(SL,"author.authorName",True) # '$author.authorName' on line 18, col 16
            if _v is not None: write(_filter(_v, rawExpr='$author.authorName')) # from line 18, col 16.
            write('''
''')
        else: # generated from line 19, col 1
            write('''New author...
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        

    def body(self, **KWS):



        ## CHEETAH: generated from #def body at line 24, col 1.
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        try: # generated from line 25, col 1
            assert VFFSL(SL,"author",True)
            author_defined = True
        except AssertionError: # generated from line 28, col 1
            author_defined = False
        if not VFFSL(SL,"new_author",True): # generated from line 31, col 1
            write('''<h1>Author record for ''')
            _v = VFFSL(SL,"author.authorName",True) # '${author.authorName}' on line 32, col 23
            if _v is not None: write(_filter(_v, rawExpr='${author.authorName}')) # from line 32, col 23.
            write('''</h1>
''')
        else: # generated from line 33, col 1
            write('''<h1>New author record</h1>
''')
        write('''<form class=\'editform\' class=\'editform\' method="get" action="/authoredit">
''')
        if not VFFSL(SL,"new_author",True): # generated from line 37, col 1
            _v = VFN(VFFSL(SL,"author",True),"object_to_form",False)(**{'title_id':VFFSL(SL,"title_id",True)}) # "$author.object_to_form(**{'title_id':$title_id})" on line 38, col 1
            if _v is not None: write(_filter(_v, rawExpr="$author.object_to_form(**{'title_id':$title_id})")) # from line 38, col 1.
            write('''
''')
        else: # generated from line 39, col 1
            _v = VFN(VFFSL(SL,"Author",True),"class_to_form",False)(**{'title_id':VFFSL(SL,"title_id",True)}) # "$Author.class_to_form(**{'title_id':$title_id})" on line 40, col 1
            if _v is not None: write(_filter(_v, rawExpr="$Author.class_to_form(**{'title_id':$title_id})")) # from line 40, col 1.
            write('''
''')
        write('''</form>
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        

    def writeBody(self, **KWS):



        ## CHEETAH: main method generated for this template
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        # Edit Author information
        write('''



''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_AuthorEditTemplate= 'writeBody'

## END CLASS DEFINITION

if not hasattr(AuthorEditTemplate, '_initCheetahAttributes'):
    templateAPIClass = getattr(AuthorEditTemplate, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(AuthorEditTemplate)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://cheetahtemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=AuthorEditTemplate()).run()


