#!/bin/bash
WD1=$PWD
if [[ $(pwd) =~ (.*/infoshopkeeper)(.*) ]]; then cd ${BASH_REMATCH[1]};  fi
#cd ~mkapes/Documents/Developer/git_repos/infoshopkeeper/inventoryserver
cheetah compile -R --nobackup
cd $WD1
if [[ -n $(which apache2ctl) ]]; then 
    sudo apache2ctl graceful
else
    if [[ -n $(which apachectl) ]]; then 
        sudo apachectl graceful
    fi
fi
